# EDA

In [3]:
import pandas as pd
import numpy as np

In [9]:
_ROOT_DIR = "./../"

In [ ]:
df = pd.read_csv(_ROOT_DIR+"./data/raw/main.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780060 entries, 0 to 780059
Data columns (total 92 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   customer_id  780060 non-null  object
 1   usage_type   780060 non-null  object
 2   Day_1        780060 non-null  float64
 3   Day_2        780060 non-null  float64
 4   Day_3        780060 non-null  float64
 5   Day_4        780060 non-null  float64
 6   Day_5        780060 non-null  float64
 7   Day_6        780060 non-null  float64
 8   Day_7        780060 non-null  float64
 9   Day_8        780060 non-null  float64
 10  Day_9        780060 non-null  float64
 11  Day_10       780060 non-null  float64
 12  Day_11       780060 non-null  float64
 13  Day_12       780060 non-null  float64
 14  Day_13       780060 non-null  float64
 15  Day_14       780060 non-null  float64
 16  Day_15       780060 non-null  float64
 17  Day_16       780060 non-null  float64
 18  Day_17       780060 non-null  float64
 19  Day_18       780060 non-null  float64
 20  Day_19       780060 non-null  float64
 21  Day_20       780060 non-null  float64
 22  Day_21       780060 non-null  float64
 23  Day_22       780060 non-null  float64
 24  Day_23       780060 non-null  float64
 25  Day_24       780060 non-null  float64
 26  Day_25       780060 non-null  float64
 27  Day_26       780060 non-null  float64
 28  Day_27       780060 non-null  float64
 29  Day_28       780060 non-null  float64
 30  Day_29       780060 non-null  float64
 31  Day_30       780060 non-null  float64
 32  Day_31       780060 non-null  float64
 33  Day_32       780060 non-null  float64
 34  Day_33       780060 non-null  float64
 35  Day_34       780060 non-null  float64
 36  Day_35       780060 non-null  float64
 37  Day_36       780060 non-null  float64
 38  Day_37       780060 non-null  float64
 39  Day_38       780060 non-null  float64
 40  Day_39       780060 non-null  float64
 41  Day_40       780060 non-null  float64
 42  Day_41       780060 non-null  float64
 43  Day_42       780060 non-null  float64
 44  Day_43       780060 non-null  float64
 45  Day_44       780060 non-null  float64
 46  Day_45       780060 non-null  float64
 47  Day_46       780060 non-null  float64
 48  Day_47       780060 non-null  float64
 49  Day_48       780060 non-null  float64
 50  Day_49       780060 non-null  float64
 51  Day_50       780060 non-null  float64
 52  Day_51       780060 non-null  float64
 53  Day_52       780060 non-null  float64
 54  Day_53       780060 non-null  float64
 55  Day_54       780060 non-null  float64
 56  Day_55       780060 non-null  float64
 57  Day_56       780060 non-null  float64
 58  Day_57       780060 non-null  float64
 59  Day_58       780060 non-null  float64
 60  Day_59       780060 non-null  float64
 61  Day_60       780060 non-null  float64
 62  Day_61       780060 non-null  float64
 63  Day_62       780060 non-null  float64
 64  Day_63       780060 non-null  float64
 65  Day_64       780060 non-null  float64
 66  Day_65       780060 non-null  float64
 67  Day_66       780060 non-null  float64
 68  Day_67       780060 non-null  float64
 69  Day_68       780060 non-null  float64
 70  Day_69       780060 non-null  float64
 71  Day_70       780060 non-null  float64
 72  Day_71       780060 non-null  float64
 73  Day_72       780060 non-null  float64
 74  Day_73       780060 non-null  float64
 75  Day_74       780060 non-null  float64
 76  Day_75       780060 non-null  float64
 77  Day_76       780060 non-null  float64
 78  Day_77       780060 non-null  float64
 79  Day_78       780060 non-null  float64
 80  Day_79       780060 non-null  float64
 81  Day_80       780060 non-null  float64
 82  Day_81       780060 non-null  float64
 83  Day_82       780060 non-null  float64
 84  Day_83       780060 non-null  float64
 85  Day_84       780060 non-null  float64
 86  Day_85       780060 non-null  float64
 87  Day_86       780060 non-null  float64
 88  Day_87       780060 non-null  float64
 89  Day_88       780060 non-null  float64
 90  Day_89       780060 non-null  float64
 91  Day_90       780060 non-null  float64
dtypes: float64(90), object(2)
memory usage: 547.5+ MB

In [32]:
# 사용량이 없는 경우 행 존재 여부 확인
count1 = df[df['usage_type'] == 'usage_app_other'].count() 
count2 = df[df['usage_type'] == 'usage_app_youtube_daily'].count()
count3 = df[df['usage_type'] == 'usage_app_facebook_daily'].count()
count4 = df[df['usage_type'] == 'usage_app_tiktok_daily'].count()
count5 = df[df['usage_type'] == 'usage_app_whatsapp_daily'].count()
count6 = df[df['usage_type'] == 'usage_app_helakuru_daily'].count()
count7 = df[df['usage_type'] == 'usage_voice_d2d_outgoing'].count()
count8 = df[df['usage_type'] == 'usage_voice_d2nd_outgoing'].count()
count9 = df[df['usage_type'] == 'usage_voice_d2d_incoming'].count()
count10 = df[df['usage_type'] == 'usage_voice_nd2d_incoming'].count()
count11 = df[df['usage_type'] == 'usage_pack_data'].count()
count12 = df[df['usage_type'] == 'usage_pack_vas'].count()


print(count1, count2, count3, count4, count5, count6, count7, count8, count9, count10, count11, count12)

customer_id    65005
usage_type     65005
Day_1          65005
Day_2          65005
Day_3          65005
               ...
Day_88         65005
Day_89         65005
Day_90         65005
day_mean       65005
avg_usage      65005
Length: 94, dtype: int64 customer_id    65005
usage_type     65005
Day_1          65005
Day_2          65005
Day_3          65005
               ...
Day_88         65005
Day_89         65005
Day_90         65005
day_mean       65005
avg_usage      65005
Length: 94, dtype: int64 customer_id    65005
usage_type     65005
Day_1          65005
Day_2          65005
Day_3          65005
               ...
Day_88         65005
Day_89         65005
Day_90         65005
day_mean       65005
avg_usage      65005
Length: 94, dtype: int64 customer_id    65005
usage_type     65005
Day_1          65005
Day_2          65005
Day_3          65005
               ...
Day_88         65005
Day_89         65005
Day_90         65005
day_mean       65005
avg_usage      65005
Length: 94, dtype: int64 customer_id    65005
usage_type     65005
Day_1          65005
Day_2          65005
Day_3          65005
               ...
Day_88         65005
Day_89         65005
Day_90         65005
day_mean       65005
avg_usage      65005
Length: 94, dtype: int64 customer_id    65005
usage_type     65005
Day_1          65005
Day_2          65005
Day_3          65005
               ...
Day_88         65005
Day_89         65005
Day_90         65005
day_mean       65005
avg_usage      65005
Length: 94, dtype: int64 customer_id    65005
usage_type     65005
Day_1          65005
Day_2          65005
Day_3          65005
               ...
Day_88         65005
Day_89         65005
Day_90         65005
day_mean       65005
avg_usage      65005
Length: 94, dtype: int64 customer_id    65005
usage_type     65005
Day_1          65005
Day_2          65005
Day_3          65005
               ...
Day_88         65005
Day_89         65005
Day_90         65005
day_mean       65005
avg_usage      65005
Length: 94, dtype: int64 customer_id    65005
usage_type     65005
Day_1          65005
Day_2          65005
Day_3          65005
               ...
Day_88         65005
Day_89         65005
Day_90         65005
day_mean       65005
avg_usage      65005
Length: 94, dtype: int64 customer_id    65005
usage_type     65005
Day_1          65005
Day_2          65005
Day_3          65005
               ...
Day_88         65005
Day_89         65005
Day_90         65005
day_mean       65005
avg_usage      65005
Length: 94, dtype: int64 customer_id    65005
usage_type     65005
Day_1          65005
Day_2          65005
Day_3          65005
               ...
Day_88         65005
Day_89         65005
Day_90         65005
day_mean       65005
avg_usage      65005
Length: 94, dtype: int64 customer_id    65005
usage_type     65005
Day_1          65005
Day_2          65005
Day_3          65005
               ...
Day_88         65005
Day_89         65005
Day_90         65005
day_mean       65005
avg_usage      65005
Length: 94, dtype: int64

In [34]:
# 행/열 pivot
# 1. days 평균 계산 (행 방향 평균)
day_cols = [col for col in df.columns if col.startswith('Day_')]
df['avg_usage'] = df[day_cols].mean(axis=1)

# 2. 행 열 변경
df_pivot = df.pivot_table(
    index='customer_id', 
    columns='usage_type', 
    values='avg_usage', 
    aggfunc='mean' 
)

# 3. columns.name, index 제거 
df_pivot.columns.name = None
df_pivot = df_pivot.reset_index()


df_pivot.head()

,customer_id,usage_app_facebook_daily,usage_app_helakuru_daily,usage_app_other,usage_app_tiktok_daily,usage_app_whatsapp_daily,usage_app_youtube_daily,usage_pack_data,usage_pack_vas,usage_voice_d2d_incoming,usage_voice_d2d_outgoing,usage_voice_d2nd_outgoing,usage_voice_nd2d_incoming
0,0000f727854b50bb95c054b39c1fe5c92e5ebcfa4bcb5d...,105.855778,28.986333,146.920444,166.764556,1.124444,324.373222,55.505889,34.975222,3.874444,27.151556,30.051667,14.358556
1,0001702d0abcdbeeb23f7c434aa6858030f365caf1464a...,47.046889,4.253111,42.282889,145.460333,1.449000,52.235778,41.940111,2.730222,47.111444,4.849889,2.907333,15.585556
2,0001ae52a920c36edc7ab364ea58a58ca725f0ad44c02b...,27.106556,4.364444,226.435444,121.954667,3.281778,126.553889,205.416333,9.904222,4.010111,6.840556,26.188000,21.914333
3,000205e54ddf8bc7512490895ce397647faaedc114f411...,87.094222,8.558000,211.995000,152.443222,22.899111,241.718778,117.987556,27.665667,11.996444,32.386000,43.624667,40.109556
4,0002511664bff302e40b19ed6872ad4390ac59901e55e2...,42.005778,19.180889,132.854222,118.975000,14.982444,115.952556,20.936000,34.854000,10.896333,43.818556,24.880444,11.652222

In [35]:
df_test = pd.read_csv(_ROOT_DIR+"./data/raw/test_cxid.csv")
df_train = pd.read_csv(_ROOT_DIR+"./data/raw/train_cxid.csv")
df_target = pd.concat([df_test, df_train], axis=0)
df_target.info()
df_target['churn'].value_counts()

<class 'pandas.core.frame.DataFrame'>
Index: 65005 entries, 0 to 52003
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  65005 non-null  object
 1   churn        65005 non-null  int64
dtypes: int64(1), object(1)
memory usage: 1.5+ MB

churn
0    50005
1    15000
Name: count, dtype: int64

In [38]:
df_merged = pd.merge(left=df_pivot, right=df_target,how="inner",on="customer_id",)
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65005 entries, 0 to 65004
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                65005 non-null  object
 1   usage_app_facebook_daily   65005 non-null  float64
 2   usage_app_helakuru_daily   65005 non-null  float64
 3   usage_app_other            65005 non-null  float64
 4   usage_app_tiktok_daily     65005 non-null  float64
 5   usage_app_whatsapp_daily   65005 non-null  float64
 6   usage_app_youtube_daily    65005 non-null  float64
 7   usage_pack_data            65005 non-null  float64
 8   usage_pack_vas             65005 non-null  float64
 9   usage_voice_d2d_incoming   65005 non-null  float64
 10  usage_voice_d2d_outgoing   65005 non-null  float64
 11  usage_voice_d2nd_outgoing  65005 non-null  float64
 12  usage_voice_nd2d_incoming  65005 non-null  float64
 13  churn                      65005 non-null  int64
dtypes: float64(12), int64(1), object(1)
memory usage: 6.9+ MB

In [40]:
# 수신 칼럼 합치기
df_merged['usage_voice_incoming'] = df_merged['usage_voice_d2d_incoming']+df_merged['usage_voice_nd2d_incoming']
df_merged.drop(columns=['usage_voice_d2d_incoming', 'usage_voice_nd2d_incoming'], inplace=True)
# 발신 칼럼 합치기
df_merged['usage_voice_outgoing'] = df_merged['usage_voice_d2d_outgoing']+df_merged['usage_voice_d2nd_outgoing']
df_merged.drop(columns=['usage_voice_d2d_outgoing', 'usage_voice_d2nd_outgoing'], inplace=True)
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65005 entries, 0 to 65004
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               65005 non-null  object
 1   usage_app_facebook_daily  65005 non-null  float64
 2   usage_app_helakuru_daily  65005 non-null  float64
 3   usage_app_other           65005 non-null  float64
 4   usage_app_tiktok_daily    65005 non-null  float64
 5   usage_app_whatsapp_daily  65005 non-null  float64
 6   usage_app_youtube_daily   65005 non-null  float64
 7   usage_pack_data           65005 non-null  float64
 8   usage_pack_vas            65005 non-null  float64
 9   churn                     65005 non-null  int64
 10  usage_voice_incoming      65005 non-null  float64
 11  usage_voice_outgoing      65005 non-null  float64
dtypes: float64(10), int64(1), object(1)
memory usage: 6.0+ MB

In [ ]:
# 'usage_app'으로 시작하는 모둔 칼럼들 평균
df_merged['avg_usage_app'] = df_merged.filter(like='usage_app').mean(axis=1)
# 'usage_voice'으로 시작하는 모둔 칼럼들 평균
df_merged['avg_usage_voice'] = df_merged.filter(like='usage_voice').mean(axis=1)
# 'usage_voice'으로 시작하는 모둔 칼럼들 평균
df_merged['avg_usage_voice'] = df_merged.filter(like='usage_voice').mean(axis=1)


df_merged.head()

,customer_id,usage_app_facebook_daily,usage_app_helakuru_daily,usage_app_other,usage_app_tiktok_daily,usage_app_whatsapp_daily,usage_app_youtube_daily,usage_pack_data,usage_pack_vas,churn,usage_voice_incoming,usage_voice_outgoing,avg_usage_app
0,0000f727854b50bb95c054b39c1fe5c92e5ebcfa4bcb5d...,105.855778,28.986333,146.920444,166.764556,1.124444,324.373222,55.505889,34.975222,0,18.233000,57.203222,129.004130
1,0001702d0abcdbeeb23f7c434aa6858030f365caf1464a...,47.046889,4.253111,42.282889,145.460333,1.449000,52.235778,41.940111,2.730222,1,62.697000,7.757222,48.788000
2,0001ae52a920c36edc7ab364ea58a58ca725f0ad44c02b...,27.106556,4.364444,226.435444,121.954667,3.281778,126.553889,205.416333,9.904222,1,25.924444,33.028556,84.949463
3,000205e54ddf8bc7512490895ce397647faaedc114f411...,87.094222,8.558000,211.995000,152.443222,22.899111,241.718778,117.987556,27.665667,0,52.106000,76.010667,120.784722
4,0002511664bff302e40b19ed6872ad4390ac59901e55e2...,42.005778,19.180889,132.854222,118.975000,14.982444,115.952556,20.936000,34.854000,0,22.548556,68.699000,73.991815